version: '3'
services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    volumes:
      - /path/to/your/photos:/photoprism/photos
      - /path/to/database:/photoprism/database
    ports:
      - 2342:2342
